### ISSUE TITLE
Background for generated images

### ISSUE THREAD

**Issue by Enuvesta** [sagniklp/doc3D-renderer#1]
Hi,

Can you pinpont lines of code, where background is selected and set?
Also, in render_mesh.py envlist is not used anywhere. Why so?

**Comment by sagniklp** [comment]
The background is not set while rendering. If you want to do it then add a plane under the mesh and texture the plane before rendering. You should first try it in Blender and then modify the `render_mesh.py`.
We do it after the rendering process. You can calculate a foreground mask from the WC or UV. Use the mask to change the background.

envlist is used here to set the environment map:
https://github.com/sagniklp/doc3D-renderer/blob/07d7ced7507757c361e30f9d9681b2e005718d4f/render_mesh.py#L134

**Comment by Enuvesta** [comment]
When I try to generate several images with `render_mesh.py` they all have different backgrounds: stones, wall, carpet (?) and etc. I wonder, where do this images come from? 
Also, if you make background after rendering part, does it mean that foreground and background has different light settings?
