### ISSUE TITLE
Customized dataset preparation

### ISSUE THREAD

**Issue by blueclowd** [sagniklp/doc3D-renderer#4]
Dear authors, 

Thanks for releasing such a fantastic job. After going through the work, I am wondering if we have to prepare all the following information:

- 3D Coordinates
- Depth
- UV
- Backward Mapping
- Albedo
- Normals
- Checkerboard

apart from the image itself to train our own model? Most of the time we have only the images and manually labeled 2D coordinates. Is there any workaround to address this issue? Thanks

**Comment by Zhang-O** [comment]
> Dear authors,
> 
> Thanks for releasing such a fantastic job. After going through the work, I am wondering if we have to prepare all the following information:
> 
> * 3D Coordinates
> * Depth
> * UV
> * Backward Mapping
> * Albedo
> * Normals
> * Checkerboard
> 
> apart from the image itself to train our own model? Most of the time we have only the images and manually labeled 2D coordinates. Is there any workaround to address this issue? Thanks

It is a complex process if you recieve no guidence from author.

**Comment by sagniklp** [comment]
@blueclowd @Zhang-O 
To train dewarpnet you need 3D Coordinates, Backward Mapping and Checkerboard images. To generate the backward mapping you need to render UV. You may not use checkerboard images but the behavior of the L1 reconstruction loss becomes ambiguous.
To train the shading removal you'll need Normals and Albedo.

If you have dense 2D coordinates then you could computationally create backward mapping, and use that as groundtruth to train dewarpnet. The main contribution of dewarpnet is using 3D coordinates as intermediate representation for unwarping. If you don't have 3D you could augment your dataset with doc3D and train dewarpnet while calculating the WC loss only on the synthetic examples.
