### ISSUE TITLE
What is the meaning of <folder-it> <start-mesh> <end-mesh>?

### ISSUE THREAD

**Issue by Ashzermcom** [sagniklp/doc3D-renderer#6]
Dear authors,

Thanks for your outstanding work. I am wondering how to render the images. What is the meaning of <folder-it> <start-mesh> <end-mesh>? I tried blender --background --python render_mesh.py -- 0 0 0; However it doesn't work. Sincerely looking forward to your reply.

**Comment by sagniklp** [comment]
you need the meshes to render images. <start-mesh> <end-mesh> refers to mesh-ids. Suppose you have 1000 meshes. you want to render for first 500 meshes, then you should use blender --background --python render_mesh.py -- 0 0 500. <folder-id> is the name of the folder the images will be saved to.

**Comment by Ashzermcom** [comment]
Thanks，how can I run this command blender in the terminal？ By using the blender app？Actually， I download the blender, but when I run this command in terminal, it also says zsh：command not found： blender. Sincerely thanks

**Comment by sagniklp** [comment]
Just add blender executable to your bashrc (Linux) to enable blender command. 
OSX: https://blender.stackexchange.com/questions/2078/how-to-use-blender-command-lines-in-osx
Win: https://blender.stackexchange.com/questions/105634/blender-is-not-recognized-as-an-internal-or-external-command-error-when-usin

**Comment by Ashzermcom** [comment]
Hello, thanks for your patience.  I try to use blender to simulate the deformation of paper, but it can't provide vivid folding details. Would you mind sharing part of your obj files? Again, sincerely thanks for your help.
