### ISSUE TITLE
ModuleNotFoundError: No module named 'bpy'

### ISSUE THREAD

**Issue by lipeng1109** [sagniklp/doc3D-renderer#7]
I Cant't install for bpy,execut "pip install bpy" is fail,please help me

**Comment by naiiytom** [comment]
@lipeng1109 you should install blender first (v2.78 should work fine https://github.com/cvlab-stonybrook/DewarpNet/issues/12#issuecomment-617597486 )
and then call python under blender using `blender --python`

**Comment by lipeng1109** [comment]
> @ lipeng1109，您应该先安装搅拌器（v2.78应该可以正常工作[cvlab-stonybrook / DewarpNet＃12（评论）](https://github.com/cvlab-stonybrook/DewarpNet/issues/12#issuecomment-617597486)）
> ，然后使用以下命令在搅拌器下调用python`blender --python`

thanks

**Comment by lipeng1109** [comment]
about step2: List the assets in objs.csv,envs.csv, and texs.csv. Can you provide an example?
step3a: blender --background --python render_mesh.py -- <folder-id> <start-mesh> <end-mesh> About folder-id
its meaning?Can you give an example to explain it in detail?This job is very interesting. Thank you very much for your help

**Comment by naiiytom** [comment]
> about step2: List the assets in objs.csv,envs.csv, and texs.csv. Can you provide an example?

You can see these files in the root of the project directory

> step3a: blender --background --python render_mesh.py -- About folder-id
> its meaning?Can you give an example to explain it in detail?This job is very interesting. Thank you very much for your help

about folder id you can refer to this issue https://github.com/sagniklp/doc3D-renderer/issues/6
